# Telco Customer Churn - Data Loading & Understanding

### Objective:

#### The goal of this project is to predict customer churn in a telecom company. By identifying customers at risk of churning, the company can take proactive steps to improve retention.

#### Note:
##### The raw dataset is not included in this repository.

In [21]:
# Import required libraries
import pandas as pd

In [22]:
# Display all columns
pd.set_option('display.max_columns', None)

### 1. Data Loading

In [23]:
# Load raw dataset
df = pd.read_excel("../data/raw/Telco_customer_churn.xlsx")
df.head(3)

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,No,No,Yes,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,No,No,Yes,8,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved

### 2. Dataset Overview

In [24]:
# Dataset shape
df.shape

(7043, 33)

In [25]:
# Column names
df.columns

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason'],
      dtype='object')

### 3. Data Inspection

In [26]:
# Overview of dataset structure
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

In [27]:
# Summary statistics for numerical and categorical features 
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
CustomerID,7043,7043,3668-QPYBK,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Count,7043.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
Country,7043,1,United States,7043,NaN,NaN,NaN,NaN,NaN,NaN,NaN
State,7043,1,California,7043,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,7043,1129,Los Angeles,305,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zip Code,7043.0,NaN,NaN,NaN,93521.964646,1865.794555,90001.0,92102.0,93552.0,95351.0,96161.0
Lat Long,7043,1652,"33.964131, -118.272783",5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Latitude,7043.0,NaN,NaN,NaN,36.282441,2.455723,32.555828,34.030915,36.391777,38.224869,41.962127
Longitude,7043.0,NaN,NaN,NaN,-119.79888,2.157889,-124.301372,-121.815412,-119.730885,-118.043237,-114.192901
Gender,7043,2,Male,3555,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Senior Citizen,7043,2,No,5901,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Partner,7043,2,No,3641,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dependents,7043,2,No,5416,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tenure Months,7043.0,NaN,NaN,NaN,32.371149,24.559481,0.0,9.0,29.0,55.0,72.0
Phone Service,7043,2,Yes,6361,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Multiple Lines,7043,3,No,3390,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Internet Service,7043,3,Fiber optic,3096,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Online Security,7043,3,No,3498,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Online Backup,7043,3,No,3088,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Device Protection,7043,3,No,3095,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tech Support,7043,3,No,3473,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Streaming TV,7043,3,No,2810,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Streaming Movies,7043,3,No,2785,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Contract,7043,3,Month-to-month,3875,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Paperless Billing,7043,2,Yes,4171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Method,7043,4,Electronic check,2365,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Monthly Charges,7043.0,NaN,NaN,NaN,64.761692,30.090047,18.25,35.5,70.35,89.85,118.75
Total Charges,7043.0,6531.0,20.2,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Churn Label,7043,2,No,5174,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Churn Value,7043.0,NaN,NaN,NaN,0.26537,0.441561,0.0,0.0,0.0,1.0,1.0
Churn Score,7043.0,NaN,NaN,NaN,58.699418,21.525131,5.0,40.0,61.0,75.0,100.0
CLTV,7043.0,NaN,NaN,NaN,4400.295755,1183.057152,2003.0,3469.0,4527.0,5380.5,6500.0
Churn Reason,1869,20,Attitude of support person,192,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
# Check for missing values in each column
df.isnull().sum()

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [29]:
# Distribution of target variable
df['Churn Value'].value_counts()

Churn Value
0    5174
1    1869
Name: count, dtype: int64

#### Key Observations

 - The dataset contains **7043 customer records** with **33 columns**.
 - There are **32 feature variables** and **1 target variable**.
 - The target variable is **'Churn Value'**, where:
    - 1 indicates customer churn
    - 0 indicates customer retention
      
 - The dataset containes **9 numerical features** (3 float, 6 integer) and **24 categorical features**.
 
 - Most columns do not contain missing values.
 - The **'Churn Reason'** has **5174 missing values**, which likely correspond to customers who do not churn.
 - The missing values in **'Churn Reason'** are expected, since churn reasons are only recorded for customers who have churned.